# Generated by Django 4.2.13 on 2024-12-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'На модерации'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=10),
        ),
    ]
